version: '3.8'

services:
  # PHP Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bagus-devlab/skc-revisi:latest
    container_name: skc-app
    restart: always
    volumes:
      # Mount storage and database for persistence
      - ./database:/var/www/database
      - ./storage:/var/www/storage
    env_file:
      - .env
    networks:
      - app_network

  # Nginx Web server service
  web:
    image: nginx:alpine
    container_name: skc-web
    restart: always
    ports:
      - "8091:80"  # Expose port 8091 on the host
    volumes:
      # Mount the production Nginx configuration
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge