version: '3.8'

services:
  app:
    image: ghcr.io/bagus-devlab/skc-revisi:latest
    container_name: skc-app
    restart: always
    volumes:
      # Mount folder database agar SQLite tidak hilang saat redeploy
      - ./database:/var/www/database
      - ./storage:/var/www/storage
    env_file:
      - .env
    networks:
      - app_network

  web:
    image: nginx:alpine
    container_name: nama_aplikasi_nginx
    restart: always
    ports:
      - "8091:80"  # Port 8091 di VPS akan mengarah ke Nginx container ini
    volumes:
      - ./public:/var/www/public # Opsional, untuk sinkronisasi static file
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge